FROM python:3.10-slim

WORKDIR /app

COPY requirements.base.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY models/ ./models/
COPY utils/ ./utils/
COPY eta_scheduler.py .
COPY eta_pipeline.py .
COPY eta_telegram_notifier.py .

CMD ["python", "-u", "eta_scheduler.py"]
