@'
events {}
http {
    upstream backend {
        server eta-api:8001;
        server optimasi-api:8002;
        server anomali-api:8003;
    }
    server {
        listen 80;
        location /api/ {
            proxy_pass http://backend/;
        }
    }
}
'@ | Out-File -FilePath nginx\nginx.conf -Encoding ascii